services:

  api:
    build: .
    container_name: outsera-backend-test
    ports:
      - "3000:3000"
    profiles:
      - prod

  api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: outsera-backend-test-dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev